### ISSUE TITLE
Error in settings with missing app icon

### ISSUE THREAD

**Issue by gregthwuen** [LynithDev/gnome-app-hider#4]
When opening the extension settings after having hidden a few applications, I get the following error:
```
TypeError: appInfo.get_icon() is null
```

Stack trace:
```
fillPreferencesWindow@/home/gtw/.local/share/gnome-shell/extensions/app-hider@lynith.dev/prefs.js:28:36
_init@resource:///org/gnome/Shell/Extensions/js/extensionPrefsDialog.js:27:29
ExtensionPrefsDialog@resource:///org/gnome/Shell/Extensions/js/extensionPrefsDialog.js:10:4
OpenExtensionPrefsAsync@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:124:33
async*LaunchExtensionPrefsAsync@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:110:14
_handleMethodCall@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:368:35
_wrapJSObject/<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:401:34
run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:186:20
main@resource:///org/gnome/Shell/Extensions/js/main.js:22:13
run@resource:///org/gnome/gjs/modules/script/package.js:206:19
start@resource:///org/gnome/gjs/modules/script/package.js:190:8
@/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
```

The culprit seems to be `xdvi.desktop` (provided by TeX Live), since the error doesn't occur when removing it from the hidden apps list.

```
[Desktop Entry]
Name=XDvi
GenericName=DVI Viewer
Exec=xdvi %f
Type=Application
Terminal=false
Categories=Graphics;Viewer;
Keywords=documents;
```

I'm on the latest release 4, installed from the Gnome extensions website and I can confirm it contains the fix dfd108c09277b32ecd7f35a44b67798c254d22eb by looking at the code.

**Comment by LynithDev** [comment]
I swear I fixed this, well guess not.

Thanks for reporting it I'll fix it when I get time

**Comment by gregthwuen** [comment]
> P.S: If it doesn't work then it's probably because I forgot to call `.to_string()` after it, my bad. (I'm currently doing this on my phone so I don't have any way to test atm)

The hidden apps list is shown without error when additionally calling `.toString()` (not `.to_string()`), thanks! Funnily, now the only icon displayed correctly is the one missing, but that works for me for now.

![image](https://user-images.githubusercontent.com/41543402/233011562-339e6363-9fc6-421f-858f-76747afb9d2b.png)

P.S. Here in the repo the extension's UUID is `app-hider-dev@lynith.dev` while the README instructs you to move the extension to `app-hider@lynith.dev`, so I guess that's outdated information.

**Comment by LynithDev** [comment]
Where did you add `.toString()`? Did you just change `.to_string()`

**Comment by gregthwuen** [comment]
I thought the `.to_string()` may have been responsible for the error from the start, but replacing it with `.toString()` also didn't fix anything, so your commit definitely is a step in the right direction.

**Comment by LynithDev** [comment]
The error with your modification occurs because you forgot to add parantheses to `get_icon`. You wrote `appInfo.get_icon.to_string()` whereas it should be `appInfo.get_icon().to_string()`. Just tested it on a live install of fedora 38 and it should work. Let me make a commit real quick

**Comment by LynithDev** [comment]
Could you pull and reload and check now?

**Comment by gregthwuen** [comment]
> The error with your modification occurs because you forgot to add parantheses to `get_icon`. You wrote `appInfo.get_icon.to_string()` whereas it should be `appInfo.get_icon().to_string()`. Just tested it on a live install of fedora 38 and it should work. Let me make a commit real quick

My mistake, I don't have any JavaScript experience. Now everything works as expected. Thanks again!
